Config=
{
    luaPath="lualib/?.lua;./?.lua",
    cPath="libs/?.so;libs/?.dll",
    start="example/clusterBoot.lua",
    thread=3,
    servicePath=
    {
        "example/services",
        "services"
    },
    args=
    {
        "main",
        "clusterReceiver.lua",
        1,
    },
}