Config=
{
    luaPath="lualib/?.lua;./?.lua",
    cPath="libs/?.so;libs/?.dll",
    start="example/clusterSender.lua",
    thread=2,
    servicePath=
    {
        "example/services",
        "services"
    },
    args=
    {
        2
    },
}